Repository joycehwchan/minanoka, pull requests merged in 2022-11, with the labels that each got.

#133 Image bug and removed the usages of "featured_img"
  app/controllers/fields_controller.rb
  app/views/fields/_card.html.erb
  app/views/fields/_map_popup.html.erb
Labels: bug, enhancement

#136 fixed more with featured_img
  app/views/bookings/_card.html.erb
Labels: bug

#135 Tried to improve the labels on Field#new
  app/views/fields/new.html.erb
Labels: enhancement

#137 restyle map popup display
  app/assets/stylesheets/components/_card.scss
  app/assets/stylesheets/components/_map_popup.scss
  app/views/fields/_map_marker.html.erb
  app/views/fields/_map_popup.html.erb
Labels: enhancement

#139 Fixed the featured_img again...
  app/views/bookings/_card.html.erb
  app/views/fields/_map_popup.html.erb
  db/schema.rb
Labels: bug

#141 Secured the params for creating new fields (removed user_id)
  app/controllers/fields_controller.rb
Labels: security

#140 show edit&cancel btns only for renter's pending status
  app/assets/stylesheets/pages/_bookings_index.scss
  app/views/bookings/_card.html.erb
Labels: enhancement

#145 Add days counte in form booking
  app/javascript/controllers/total_controller.js
  app/models/booking.rb
  app/views/bookings/_edit_form.html.erb
  app/views/bookings/_form.html.erb
Labels: bug, enhancement

#148 Fixed the restriction for field reviews
  app/models/review.rb
Labels: enhancement

#150 Edit field bug
  app/policies/review_policy.rb
  app/views/fields/_form.html.erb
  config/routes.rb
Labels: bug

#153 Added reviews to seeds, and fixed some other minor things
  db/seeds.rb
Labels: bug, enhancement

#154 added more content on fields#show
  app/assets/stylesheets/components/_icon.scss
  app/assets/stylesheets/components/_index.scss
  app/views/fields/show.html.erb
Labels: enhancement

#155 Updated the fake stuff for the field#show,
  app/views/fields/_animals_nearby.html.erb
  app/views/fields/_what_to_grow.html.erb
  app/views/fields/show.html.erb
Labels: enhancement

#156 Added pluralize to the animals
  app/views/fields/_animals_nearby.html.erb
Labels: enhancement

#157 Added pluralize to the things you can grow
  app/views/fields/_what_to_grow.html.erb
Labels: enhancement

#163 Field info
  app/views/fields/show.html.erb
Labels: enhancement

#164 Added a space between the carrot and the rating
  app/views/fields/_card.html.erb
  app/views/fields/show.html.erb
Labels: enhancement

#165 Added some style to field#show
  app/assets/stylesheets/components/_index.scss
  app/assets/stylesheets/components/_review.scss
  app/views/fields/show.html.erb
  app/views/reviews/_form.html.erb
  app/views/reviews/_review.html.erb
Labels: enhancement

#167 Added some things to the random arrays
  app/views/fields/_animals_nearby.html.erb
  app/views/fields/show.html.erb
Labels: enhancement

#168 Updated seed
  db/seeds.rb
Labels: enhancement

#170 added name to update user details
  app/controllers/application_controller.rb
  app/views/devise/registrations/edit.html.erb
  app/views/landowner/bookings/index.html.erb
Labels: bug

#172 updated the page for bookings
  app/views/landowner/bookings/index.html.erb
Labels: bug

#173 removed button for signup on homepage
  app/views/pages/home.html.erb
Labels: bug
